blog/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

blog/articles/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('new/', views.article_edit, name='new'),
    url(r'^edit/(?P<id>\d+)/$', views.article_edit, name='edit'),
    url(r'^delete-article/(?P<article_id>\d+)/$', views.delete_article, name='delete_article'),
    url(r'^delete-comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),
    url(r'^add-reaction/(?P<reaction_type>[\w-]+)/(?P<slug>[\w-]+)/$', views.add_reaction, name='add_reaction'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from articles import views as article_views

handler404 = 'blog.views.handler404'
#handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', article_views.article_list, name='home'),
]

blog/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </link>
    <title>Websited</title>
</head>

<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="websited" /></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Wyloguj się</button>
                    </form>
                </li>
                {% if user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">Panel Administracyjny</a></li>
                <li><a href="{% url 'articles:new' %}" class="highlight">Nowy artykuł</a></li>
                {% endif %}

                {% else %}
                <li><a href="{% url 'accounts:login' %}">Zaloguj się</a></li>
                <li><a href="{% url 'accounts:register' %}">Zarejestruj się</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper my-5 pb-5">
        {% block content %}
        {% endblock %}
    </div>


    <footer class="page-footer font-small blue navbar fixed-bottom row bg-dark">
        <div class="footer-copyright text-center py-3 col-6 offset-3">© 2020:
            <a href="https://github.com/wszeborowskimateusz/"> Mateusz Wszeborowski 165562 | </a>
            <a href="https://icons8.com/"> Ikonki</a>
        </div>
    </footer>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
</body>

</html>