blog/articles/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('new/', views.article_edit, name='new'),
    url(r'^edit/(?P<id>\d+)/$', views.article_edit, name='edit'),
    url(r'^delete-article/(?P<article_id>\d+)/$', views.delete_article, name='delete_article'),
    url(r'^delete-comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),
    url(r'^add-reaction/(?P<reaction_type>[\w-]+)/(?P<slug>[\w-]+)/$', views.add_reaction, name='add_reaction'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from articles import views as article_views

handler404 = 'blog.views.handler404'
#handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', article_views.article_list, name='home'),
]

blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class CustomDateTimeField(models.DateTimeField):
    def value_to_string(self, obj):
        val = self.value_from_object(obj)
        if val:
            val.replace(microsecond=0)
            return val.strftime("%d-%m-%y, %H:M")
        return ''

class Article(models.Model):
    class Meta:
        verbose_name = "Artykuł"
        verbose_name_plural = "Artykuły"

    title = models.CharField(max_length=100, verbose_name="Tytuł")
    slug = models.SlugField(verbose_name="Tytuł w pasku adresowym")
    content = models.TextField(verbose_name="Treść")
    timestamp = CustomDateTimeField(auto_now_add=True, verbose_name="Czas utworzenia")
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[:100] + "..."

class Comment(models.Model):
    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"

    timestamp = CustomDateTimeField(auto_now_add=True, verbose_name="Czas utworzenia")
    content = models.TextField(verbose_name="Treść")
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, verbose_name="Autor")
    article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE, verbose_name="Artykuł")

class Reaction(models.Model):
    class Meta:
        verbose_name = "Reakcja"
        verbose_name_plural = "Reakcje"

    class ReactionType(models.TextChoices):
        HAPPY = 'HP', "Szczęśliwy"
        SAD = 'SD', 'Smutny'
        NEUTRAL = 'NT', 'Neutralny'


    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE)
    reaction_type = models.CharField(
        max_length=2,
        choices = ReactionType.choices,
        default = ReactionType.HAPPY,
    )

blog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'content', 'slug']

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content']

blog/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.decorators import login_required

from .models import Article, Comment, Reaction
from .forms import CreateArticle, CreateComment


def article_list(request):
    articles = Article.objects.all().order_by('-timestamp')
    return render(request, "articles/article_list.html", {'articles': articles})

@login_required(login_url='/accounts/login/')
def article_edit(request, id=None):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    if id:
        is_edit = True
        article = get_object_or_404(Article, id=id)
    else:
        is_edit = False
        article = Article(author=request.user)
    form = CreateArticle(request.POST or None, instance=article)
    if request.method == 'POST' and form.is_valid():
        # Save to DB
        new_article = form.save(article)
        return redirect('articles:list')

    return render(request, "articles/article_new.html", {'form': form, 'is_edit': is_edit, 'article': article})


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    comments = Comment.objects.all().filter(article=article).order_by('-timestamp')
    reactions = Reaction.objects.all().filter(article=article)
    positiveReactions = reactions.filter(reaction_type=Reaction.ReactionType.HAPPY)
    neutralReactions = reactions.filter(reaction_type=Reaction.ReactionType.NEUTRAL)
    negativeReactions = reactions.filter(reaction_type=Reaction.ReactionType.SAD)

    if request.method == 'POST':
        commentForm = CreateComment(request.POST)
        if commentForm.is_valid():
            if not request.user.is_authenticated:
                return HttpResponseForbidden()
            comment = commentForm.save(commit=False)
            comment.author = request.user
            comment.article = article
            comment.save()
            return redirect('articles:detail', slug=slug)
    else:
        commentForm = CreateComment()
    return render(request, "articles/article_detail.html", 
        {'article': article, 'comments': comments, 'commentForm': commentForm, 
        'happyReactions': positiveReactions, 'neutralReactions': neutralReactions, 'sadReactions': negativeReactions})

@login_required(login_url='/accounts/login/')
def add_reaction(request, reaction_type, slug):
    if request.method == 'POST':
        article = get_object_or_404(Article, slug=slug)
        try:
            # If user already gave a reaction to this post this will not throw exception
            reaction = Reaction.objects.all().filter(article=article, author=request.user)
            reaction.delete()
        except Reaction.DoesNotExist:
            pass
        
        if reaction_type == 'positive':
            r_type = Reaction.ReactionType.HAPPY
        elif reaction_type == 'neutral': 
            r_type = Reaction.ReactionType.NEUTRAL
        elif reaction_type == 'negative':
            r_type = Reaction.ReactionType.SAD
        new_reaction = Reaction(article=article, author=request.user, reaction_type=r_type)
        new_reaction.save()

        print(f"Got reaction: {reaction_type} to article with slug {slug} from user {request.user}")
        return redirect('articles:detail', slug=slug)

@login_required(login_url='/accounts/login/')
def delete_comment(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        if (not request.user.is_superuser) and (comment.author != request.user):
            return HttpResponseForbidden()
        slug = comment.article.slug 
        comment.delete()
        return redirect('articles:detail', slug=slug)

@login_required(login_url='/accounts/login/')
def delete_article(request, article_id):
    if request.method == 'POST':
        if not request.user.is_superuser:
            return HttpResponseForbidden()
        article = get_object_or_404(Article, id=article_id)
        article.delete()
        return redirect('articles:list')

blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
<main>
    <div class="article_detail">
        <div class="article">
            <header>
                <h1>{{article.title}}</h1>
            </header>
            {% if user.is_superuser %}
            <div class="float-right">
                <form class="" action="{% url 'articles:delete_article' article_id=article.id %}" method="post"
                    onsubmit="return confirm('Czy na pewno chcesz usunąć ten artykuł?');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger m-2">Usuń artykuł</button>
                </form>
            </div>
            <a class="btn btn-warning mb-2" href="{% url 'articles:edit' id=article.id %}">Edytuj</a>
            {% endif %}
            <section class="article_detail">
                <div class="mb-3">{{article.timestamp}}</div>
                <p class="article__snippet">{{article.content}}</p>
            </section>
        </div>
    </div>
    {% if user.is_authenticated %}
    <div class="row my-3">
        <div class="col-4 text-center">
            <form class="" action="{% url 'articles:add_reaction' slug=article.slug reaction_type='positive'%}"
                method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">
                    <p>Szczęśliwy</p>
                    <p>({{happyReactions|length}})</p>
                    <img src="{% static 'happy.png' %}" alt="szczęśliwy">
                </button>
            </form>
        </div>
        <div class="col-4 text-center">
            <form class="" action="{% url 'articles:add_reaction' slug=article.slug reaction_type='neutral'%}"
                method="post">
                {% csrf_token %}
                <button class="btn btn-secondary">
                    <p>Neutralny</p>
                    <p>({{neutralReactions|length}})</p>
                    <img src="{% static 'neutral.png' %}" alt="neutralny">
                </button>
            </form>
        </div>
        <div class="col-4 text-center">
            <form class="" action="{% url 'articles:add_reaction' slug=article.slug reaction_type='negative' %}"
                method="post">
                {% csrf_token %}
                <button class="btn btn-danger">
                    <p>Smutny</p>
                    <p>({{sadReactions|length}})</p>
                    <img src="{% static 'sad.png' %}" alt="smutny">
                </button>
            </form>
        </div>
    </div>
    {% endif %}
    <h2 class="py-2">Komentarze:</h2>
    <div class="article_comments">
        {% for comment in comments%}
        <div class="border p-2 my-4">
            <h5>Autor: {{comment.author}}</h2>
                <h6>{{comment.timestamp}}</h6>
                <h5>Treść: {{comment.content}}</h3>
                    {% if comment.author == user or user.is_superuser %}
                    <div class="d-flex flex-row-reverse">
                        <form class="" action="{% url 'articles:delete_comment' comment_id=comment.id %}" method="post"
                            onsubmit="return confirm('Czy na pewno chcesz usunąć ten komentarz?');">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger m-2">Usuń komentarz</button>
                        </form>
                    </div>
                    {% endif %}
        </div>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <form class="site-form comment-form my-3" method="post" action="{% url 'articles:detail' slug=article.slug %}">
        {% csrf_token %}
        {{commentForm}}
        <input type="submit" value="Dodaj komentarz">
    </form>
    {% endif %}
</main>
{% endblock %}

blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<main>
    <header>
        <h1>Artykuły</h1>
    </header>
    <div class="articles">
        {% for article in articles %}
        <article class="article">
            <header>
                <a href="{% url 'articles:detail' slug=article.slug %}">
                    <h2>{{article.title}}</h2>
                </a>
            </header>
            <div class="mb-3">{{article.timestamp}}</div>
            <p class="lead">{{article.snippet}}</p>
        </article>
        {% endfor %}
    </div>
</main>
{% endblock %}

blog/articles/templates/articles/article_new.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<main>
    <header>
        {% if is_edit %}
        <h1>Edytuj artykuł</h1>
        {% else %}
        <h1>Dodaj nowy wpis</h1>
        {% endif %}
    </header>
    <section>
        {% if is_edit %}
        <form class='site-form' action="{% url 'articles:edit' id=article.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Edytuj">
        </form>
        {% else %}
        <form class='site-form' action="{% url 'articles:new' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Dodaj artykuł">
        </form>
        {% endif %}
    </section>
    <script src="{% static 'js/slugify.js' %}"></script>
</main>
{% endblock %}